### ISSUE TITLE
代码请求

### ISSUE THREAD

**Issue by fqsfeng** [MTandHJ/RecBoard#1]
作者你好，再次打扰您。
我最近在尝试复现SEvo并更进一步，我在论文中看你们的工作包括将图编码器进行替换，我也在尝试将SEvo加入到图神经网络中（如LightGCN,SGL）。但是没能成功，我想请问一下作者有没有将SEvo加入到LightGCN(或者其他图模型)的代码？万分感谢。

**Comment by MTandHJ** [comment]
1. LightGCN, SGL 的代码 RecBoard 里有实现 (SGL 的代码还没有经过完全的验证), 你可以模仿着加一下, 只需要把 smoother 和 embedding 放到一起就可以了.
2. 我们将 SEvo 用在 LESSR 和 MAERec 其实主要是审稿人对这一块感兴趣, 我们主观的理解是如果一个模型本身能够很好地学习到结构信息, SEvo 的帮助应该不大. 理论上, 协同过滤中的 SOTA 的图模型应该在建模结构信息上是很强的 (甚至有些方法能够建模高频信息, 而 SEvo 本质上还是聚焦在低频信息上). LESSR 和 MAERec 上有效, 我感觉主要还是因为它们需要同时兼顾结构信息和序列信息.

你能说一下具体哪个地方扩展不顺利吗? 方便的话我可以再写一个.

**Comment by fqsfeng** [comment]
我看文章中有提到SEvo可以替代GNN，所以我想试一下用Smoother做编码器，但是我没弄明白Smoother具体是如何替代Lightgcn中的编码器，主要是这一块有点问题。

**Comment by MTandHJ** [comment]
不好意思, 我没太明白用 Smoother 做编码器的意思 (文中也没提到图编码器的替换)? SEvo 的结构替换掉 LightGCN 的结构而不是用于优化器吗?

**Comment by fqsfeng** [comment]
哦哦我明白了，意思是SEvo是集成到如SGD和adam这类优化器中，用来捕捉结构信息，与模型本身并没关系是吗？
感谢您的回答
